name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  merge_group:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: dump env and git info
        run: |
          set -x
          printenv | grep -E '^GITHUB_' | sort
          echo
          git log --graph --all --decorate=full --pretty=oneline --abbrev-commit
